### ISSUE TITLE
Font-Awesome v6

### ISSUE THREAD

**Issue by Gummibeer** [owenvoke/blade-fontawesome#30]
Thanks for thinking ahead @owenvoke ! 🙏
The package already works with Font-Awesome v6. The new `thin` set as well as all the new icons are detected by the package. As soon as FA6 is out of alpha/beta the packed-in icons could be replaced but you can already use the FA6 Pro icons with the sync pro icons command. 🎉

Right now you can only sync the pro icons with the command as it has hardcoded `fontawesome-pro` in it.
https://github.com/owenvoke/blade-fontawesome/blob/60c1f2b6629012ab4c9e6871dc911c08606d0b27/src/Commands/SyncProIconsCommand.php#L23-L25

Would it be an idea to allow to customize that one as well so that this command could be used to sync the free FA6 icons as well? 🤔

**Comment by Gummibeer** [comment]
Checked the docs and the Symfony `setAliases()` works the same in Laravel - so not a breaking change. 🥳
```php
 protected function configure(): void
{
    $this->setAliases(['old']);
}
```

**Comment by owenvoke** [comment]
Well, that would be great!
