### ISSUE TITLE
`2.x` version missing

### ISSUE THREAD

**Issue by swapnilsarwe** [owenvoke/blade-fontawesome#35]
I guess `2.x` (as mentioned in `README.md`) version seems to be missing, or is it yet to be tagged?

**Comment by victorybiz** [comment]
@owenvoke I just tried `dev-main` with Laravel 9 in an existing project upgraded from v8, it worked perfectly well as expected. Feel free to tag it.

**Comment by owenvoke** [comment]
Just tagged [`v2.0.0`](https://github.com/owenvoke/blade-fontawesome/releases/tag/v2.0.0)!
