### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by brandon-9** [owenvoke/blade-fontawesome#36]
Sorry, not a bug, but any recommended methods to help PHPStorm recognize the blade components? I'm always getting "Unknown Blade component" error for any of the icon components. Any suggestions would be much appreciated!

**Comment by owenvoke** [comment]
I'm not entirely sure, apologies! I wonder if that's something that could be added to Blade Icons in general. However, perhaps this could be done as a PhpStorm plugin / IDE helper stub.

Will see what I can find and get back to you. :+1:

**Comment by intractve** [comment]
Just as a FYI, if you want to remove errors in the meanwhile... 
`<x-dynamic-component :component="fas-home" class="h-4 w-4" />`
works beautifully

**Comment by brandon-9** [comment]
@intractve great suggestion! Thanks!

**Comment by JackWH** [comment]
After some trial and error, I finally managed to get PhpStorm (with the [Laravel Idea plugin](https://laravel-idea.com)) to autocomplete icons using the steps below:

1. Ensure `config/blade-icons.php` is published, then update it like this:

```php
'sets' => [
    'default' => [
        'path' => 'resources/icons/blade-fontawesome',
        'prefix' => 'fa',
        // ...
    ],
],

// ...

'components' => [
    'disabled' => false,
    'default' => 'fa',
],
```

2. Run these commands (with `--pro` as needed):

```sh
php artisan clear-compiled
php artisan view:clear
php artisan icons:clear
php artisan blade-fontawesome:sync-icons --pro
php artisan icons:cache
```

3. In PhpStorm's Laravel Idea settings, under the "Laravel Packages" section, configure `blade-ui-kit/blade-icons` as shown:

![Screenshot 2023-01-20 at 17 29 53@2x](https://user-images.githubusercontent.com/627533/213765026-5ab40f82-58bb-4e40-90cb-4219ac1ad500.png)

4. Click "Register Custom Blade Directives" in the Laravel Idea menu:

<img width="362" alt="Screenshot 2023-01-20 at 17 30 55@2x" src="https://user-images.githubusercontent.com/627533/213765218-72695a28-288e-4666-8f7a-a8ef984d2c82.png">

5. You can then get full autocompletion for components across every set, by referencing the icons like this:

```blade
<!-- x-fa-[directory].[icon] -->
<x-fa-solid.circle-arrow-down />
<x-fa-brands.github />
<x-fa-duotone.face-smile />
<!-- etc... -->
```

Using the `x-fa-[directory].[icon]` format lets PhpStorm recognise the icons and autocomplete them. The normal style (e.g. `<x-fas-cloud />`) still works fine too, it just won't be recognised by the IDE.

Hope that helps...!
