### ISSUE TITLE
Limit icon sets

### ISSUE THREAD

**Issue by bkilshaw** [owenvoke/blade-fontawesome#41]
Is it possible to limit what icon sets get installed? The Font Awesome Pro package especially has a ton of icons, we're looking at sets for brands, duotone, light, regular, solid, thin, and I only use two of the bunch. The issue I'm having is with Laravel Vapor your whole application is limited to 250MB and right now blade-fontawesome is eating up 77MB alone.

If there's any way in a setting or config file to limit which icon sets get installed instead of all of them?

**Comment by owenvoke** [comment]
🤔 Hmm, there isn't currently a way to do this. I'm wondering if we could split these out into separate packages somehow. For example, so you'd require `owenvoke/blade-fontawesome-solid`, and then this package would do something like:

```php
if (class_exists(\OwenVoke\BladeFontAwesome\Solid::class)) {
   // Add free Solid set
}
```

However, that'd be a breaking change. And would require new locations for the package to find the icons in. 🤷🏻 Or maybe have this package work with subtree-splitting (similar to Laravel framework).
