### ISSUE TITLE
FA v6 for Laravel 8

### ISSUE THREAD

**Issue by mattgreenfield** [owenvoke/blade-fontawesome#42]
## Description

I'm using Laravel 8, blade-fontawesome v1 and Font Awsome v5. Everything is good!

But... I have a designer asking for an icon from FA6 and I'm embarrassed to tell them how long that will take - first upgrading a major Laravel version!

I could, of course, hack it with an inlined SVG but I'd rather not. Is there any way we can get FA6 support on Laravel 8 with this package?

## Possible implementation

I appreciate this would have to be a patch for blade-fontawesome v1 but if it's only a small change it would be much appreciated!

Thank you

**Comment by owenvoke** [comment]
Hi @mattgreenfield, I am no longer using Laravel 8, so I did not want to have to support it. The current package (at v2) should be fully compatible with Laravel 8 though, so you're welcome to fork the repository and reference this with a [Composer` VCS repository](https://getcomposer.org/doc/05-repositories.md#vcs) in your project.

You should just be able to add `^8.0` here: https://github.com/owenvoke/blade-fontawesome/blob/eb8fc65b8770e794960eb34166e05f0b8ea19a9a/composer.json#L9

**Comment by mattgreenfield** [comment]
Thank you @owenvoke - this worked a treat.
The only other thing I had to do was upgrade the npm package to v6 in my projects package.json.
