### ISSUE TITLE
Path to Sharp icons is incorrect

### ISSUE THREAD

**Issue by ianlandsman** [owenvoke/blade-fontawesome#46]
## Description

The path to the sharp icons is incorrect, Font Awesome publishes it as "sharp-solid" but this package expects it to be just "sharp". 

I would have made a pr for the change, but I wasn't sure how you'd want to handle the solid aspect as I presume they may have set it that way in preparation for sharp-light, sharp-thin, etc (it does say coming soon to these on the site).

**Comment by sammyaxe** [comment]
any news on this one?

**Comment by owenvoke** [comment]
Feel free to PR a change for this if you'd like. 👍🏻

**Comment by owenvoke** [comment]
This is resolved by https://github.com/owenvoke/blade-fontawesome/pull/56 👍🏻 Released as part of v2.4.0 🚀

The new prefixes are:
- Sharp Regular (`far-sharp`)
- Sharp Light (`fal-sharp`)
- Sharp Solid (`fas-sharp`)
