### ISSUE TITLE
Font-Awesome v6.2.0

### ISSUE THREAD

**Issue by suretarget** [owenvoke/blade-fontawesome#47]
Thank you @owenvoke for the great package. 
I saw "resources/svg" already updated to v6.2.0 but when I fresh install via composer it still using v.6.0.0.
How to use the latest version?

**Comment by owenvoke** [comment]
Looks like I've forgotten to tag new versions, I'll create a new release shortly. 👍🏻

**Comment by owenvoke** [comment]
@suretarget, just released v2.1.0 with Font Awesome v6.2.0 👍🏻
