### ISSUE TITLE
Unable to locate a class or view for component [fas-cloud]

### ISSUE THREAD

**Issue by nguyentranchung** [owenvoke/blade-fontawesome#6]
## Description

I installed as instructed, but encountered an error

Facade\Ignition\Exceptions\ViewException
Unable to locate a class or view for component [fas-cloud].

## Environment

* PHP 7.4.7
* Windows 10

**Comment by nguyentranchung** [comment]
I debugged the result

![image](https://user-images.githubusercontent.com/9611224/86527854-dfcc9d00-bedd-11ea-9062-bd080ef4e5e9.png)

fab-cloud not registered

I try edit code
```php
        $this->callAfterResolving(Factory::class, function (Factory $factory) {
            $factory->add('fontawesome-brands', [
                'path' => __DIR__ . '/../resources/svg/brands',
                'prefix' => 'fab',
            ]);
            $factory->add('fontawesome-regular', [
                'path' => __DIR__ . '/../resources/svg/regular',
                'prefix' => 'far',
            ]);

            $factory->add('fontawesome-solid', [
                'path' => __DIR__ . '/../resources/svg/solid',
                'prefix' => 'fas',
            ]);


            $factory->registerComponents();
        });
```

See result:

![image](https://user-images.githubusercontent.com/9611224/86527882-15718600-bede-11ea-84d5-f5319e647166.png)

**Comment by driesvints** [comment]
Please share how you're using the icons.

**Comment by owenvoke** [comment]
Hi @nguyentranchung, I haven't been able to replicate this issue. As @driesvints mentioned, could you share how you're using the icons?

**Comment by nguyentranchung** [comment]
@driesvints @owenvoke 
I tried installing a new project so no problem happened.

But the current project has a problem, I don't understand where the problem is.
![image](https://user-images.githubusercontent.com/9611224/86792325-55369a00-c0a5-11ea-9f4c-59949e1c9d21.png)

![image](https://user-images.githubusercontent.com/9611224/86792747-bf4f3f00-c0a5-11ea-82da-d6c5455cbe7b.png)

I tried to register in blade-icons.php config.
```php
<?php

return [
    'sets' => [
        'default' => [
            'path' => 'resources/svg',
            'prefix' => 'icon',
            'class' => '',
        ],
        'fontawesome-brands' => [
            'path' => 'vendor/owenvoke/blade-fontawesome/resources/svg/brands',
            'prefix' => 'fab',
            'class' => 'icon',
        ],
        'fontawesome-regular' => [
            'path' => 'vendor/owenvoke/blade-fontawesome/resources/svg/regular',
            'prefix' => 'far',
            'class' => 'icon',
        ],
        'fontawesome-solid' => [
            'path' => 'vendor/owenvoke/blade-fontawesome/resources/svg/solid',
            'prefix' => 'fas',
            'class' => 'icon',
        ],
    ],
    'class' => '',
];
```
throw CannotRegisterIconSet
![image](https://user-images.githubusercontent.com/9611224/86793087-11906000-c0a6-11ea-8959-b7dd2bd8bc76.png)

**Comment by driesvints** [comment]
> I tried to register in blade-icons.php config.

You don't need to do that. The package does that for you. 

You still haven't shared how you're using the icons. Please share the code and tell us where and how it's being used.

**Comment by nguyentranchung** [comment]
@driesvints 
in TestController.php
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Blade;

class TestController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        dump(\Blade::debug());
        return view('test');
    }
}
```

test.blade.php
```php
<x-fas-cloud />
```
That's it

**Comment by nguyentranchung** [comment]
in vendor\owenvoke\blade-fontawesome\src\BladeFontAwesomeServiceProvider.php I add 1 line

```php
<?php

declare(strict_types=1);

namespace OwenVoke\BladeFontAwesome;

use BladeUI\Icons\Factory;
use Illuminate\Support\ServiceProvider;

final class BladeFontAwesomeServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $this->callAfterResolving(Factory::class, function (Factory $factory) {
            $factory->add('fontawesome-brands', [
                'path' => __DIR__ . '/../resources/svg/brands',
                'prefix' => 'fab',
            ]);

            $factory->add('fontawesome-regular', [
                'path' => __DIR__ . '/../resources/svg/regular',
                'prefix' => 'far',
            ]);

            $factory->add('fontawesome-solid', [
                'path' => __DIR__ . '/../resources/svg/solid',
                'prefix' => 'fas',
            ]);


            // ---------------------------------
            $factory->registerComponents();


        });

        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../resources/svg' => public_path('vendor/blade-fontawesome'),
            ], 'blade-fontawesome');
        }
    }
}
```
![image](https://user-images.githubusercontent.com/9611224/86794865-f0c90a00-c0a7-11ea-8cdd-f2fa34420c4e.png)

It will be ok.

**Comment by owenvoke** [comment]
That method is already called in [the main package](https://github.com/blade-ui-kit/blade-icons/blob/e7c20c730ba6bb929cbe246cfca7aea0834742af/src/BladeIconsServiceProvider.php#L52), so I don't see why it would need to be called again. 🤔 Any thoughts @driesvints?

**Comment by nguyentranchung** [comment]
And then I comment out it, it's still ok.
Because cache views
![image](https://user-images.githubusercontent.com/9611224/86795089-2d950100-c0a8-11ea-81c9-6dfe918b4e8f.png)
![image](https://user-images.githubusercontent.com/9611224/86795145-3c7bb380-c0a8-11ea-8254-d841a378b2d4.png)
![image](https://user-images.githubusercontent.com/9611224/86795347-6b922500-c0a8-11ea-99e9-5f4afd6c2b80.png)

**Comment by nguyentranchung** [comment]
After call
```shell
php artisan view:clear
```
![image](https://user-images.githubusercontent.com/9611224/86795553-a5632b80-c0a8-11ea-9a9a-b3530d3b5e0d.png)

**Comment by nguyentranchung** [comment]
This is my composer
```json
{
"require": {
        "php": "^7.2.5",
        "artesaos/seotools": "^0.17.2",
        "calebporzio/sushi": "^2.0",
        "davejamesmiller/laravel-breadcrumbs": "^5.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "glorand/laravel-model-settings": "^3.6",
        "guzzlehttp/guzzle": "^6.3",
        "jenssegers/agent": "^2.6",
        "kalnoy/nestedset": "^5.0",
        "kub-at/php-simple-html-dom-parser": "^1.9",
        "laracasts/flash": "^3.1",
        "laravel/framework": "^7.0",
        "laravel/scout": "^8.0",
        "laravel/socialite": "^4.4",
        "laravel/tinker": "^2.0",
        "nwidart/laravel-modules": "^7.1",
        "owenvoke/blade-fontawesome": "^1.1",
        "spatie/enum": "^2.3",
        "spatie/laravel-html": "^2.26",
        "spatie/laravel-medialibrary": "^7.19",
        "spatie/laravel-menu": "^3.5",
        "spatie/laravel-permission": "^3.13",
        "spatie/laravel-query-builder": "^2.8",
        "spatie/laravel-sitemap": "^5.7",
        "spatie/laravel-sluggable": "^2.2",
        "spatie/laravel-tags": "^2.6",
        "spatie/schema-org": "^2.14",
        "spatie/valuestore": "^1.2"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.3",
        "barryvdh/laravel-ide-helper": "^2.7",
        "beyondcode/laravel-query-detector": "^1.3",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "laravel/telescope": "^3.5",
        "laravel/ui": "^2.0",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5",
        "predis/predis": "^1.1"
    }
}
```
Is there any possibility of a conflict with another package?

**Comment by nguyentranchung** [comment]
@driesvints @owenvoke 

![image](https://user-images.githubusercontent.com/9611224/86857000-8096a480-c0f8-11ea-8e7e-e48a42d73e3b.png)

The problem occurs because provider BladeIconsServiceProvider runs before BladeFontAwesomeServiceProvider

**Comment by nguyentranchung** [comment]
But in a completely new project, I got the opposite result

![image](https://user-images.githubusercontent.com/9611224/86857282-29450400-c0f9-11ea-8fac-af362c4d16d2.png)

**Comment by nguyentranchung** [comment]
@driesvints @owenvoke 
I found the cause, this error will appear when you install the https://github.com/jeroennoten/Laravel-AdminLTE package.

**Comment by owenvoke** [comment]
@nguyentranchung, thanks for your thorough debugging of this. 🤔

Just trying to create a reproducable repository for testing, but the `almasaeed2010/adminlte` package isn't downloading from dist or source. 😐

**Comment by driesvints** [comment]
Erhm, can anyone walk me through what the adminlte package does and how it affects icons?

**Comment by nguyentranchung** [comment]
@driesvints @owenvoke 
https://github.com/jeroennoten/Laravel-AdminLTE/blob/f860d992548048836d554bfca170fde19f1c3089/src/AdminLteServiceProvider.php#L43

Because function boot injects view factory, so view is not resolved.

**Comment by driesvints** [comment]
I'm guessing this would probably be solved if we bound `Illuminate\Contracts\View\Factory` instead.

**Comment by owenvoke** [comment]
@driesvints, just tested that and it doesn't seem to resolve the issue. 🤔

I'm assuming you were meaning to try changing that in [the Blade Icons service provider](https://github.com/blade-ui-kit/blade-icons/blob/2d39b9661db3efea8df269e9566145ddb57f6e00/src/BladeIconsServiceProvider.php#L49)?

**Comment by driesvints** [comment]
yeah that's what I meant

**Comment by owenvoke** [comment]
Yeah, it still throws the same error about the component not being found. 😬

**Comment by driesvints** [comment]
I think I know where the problem lies. Can you try moving 

```php
    private function bootComponents(): void
    {
        $this->callAfterResolving(\Illuminate\Contracts\View\Factory::class, function ($view, Application $app) {
            $app->make(Factory::class)->registerComponents();
        });
    }
```

To the `register` method instead?

**Comment by owenvoke** [comment]
I've moved it into the `register` method however it still seems to throw the error. 🤨 Apologies for taking up so much of your time.

**Comment by driesvints** [comment]
No worries. I'll try it out myself when I find some free time. Appreciating any help until then.

**Comment by driesvints** [comment]
I've found the issue. The problem is indeed `boot` of Admin LTE getting executed before `boot` of blade-fontawesome. All `callAfterResolving` belong in `register` actually. I didn't thought this through enough. I'll pr a fix and patch up `blade-icons` as well.

**Comment by driesvints** [comment]
Sent in https://github.com/owenvoke/blade-fontawesome/pull/9 which solves this.

**Comment by ahmeddabak** [comment]
Just upgraded my laravel installation to V8.x. i am getting the same error when running php artisan optimize, it happens when laravel tries to cache the views.

Unable to locate a class or view for component [fas-eye].

on \src\Illuminate\View\Compilers\ComponentTagCompiler.php:274

The wierd thing is that i do not get any errors when running php artisan view:cache on its own.

so i added 

dd($this->aliases);

at vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:249

when i ran php artisan view:cache i get a long list of components, but when i ran php artisan optimize i only got 

array:1 [
  "dynamic-component" => "Illuminate\View\DynamicComponent"
]

I will try to find out what is happening

**Comment by driesvints** [comment]
@ahmeddabak we have the same issue on heroicons (and probably every blade icons library). I'm puzzled at what's causing this and appreciating any help.

https://github.com/blade-ui-kit/blade-heroicons/issues/9

**Comment by ahmeddabak** [comment]
@driesvints The error has to do with 

https://github.com/laravel/framework/blob/33cd5769505f7d908134bbcf77e24c777fa85c11/src/Illuminate/Foundation/Console/ConfigCacheCommand.php#L84

and 

https://github.com/laravel/framework/blob/33cd5769505f7d908134bbcf77e24c777fa85c11/src/Illuminate/Foundation/Console/RouteCacheCommand.php#L92

where laravel creates a new instance of the application. I still not sure how that effect the original application instance
