### ISSUE TITLE
Twitter X icon

### ISSUE THREAD

**Issue by berdancanyet** [owenvoke/blade-fontawesome#61]
[(https://blade-ui-kit.com/blade-icons?set=7&search=x)](https://blade-ui-kit.com/blade-icons?set=7&search=x)
## Description

I'm looking for the new X icon at Blade UI Kit, when is it going to be added? thanks.

**Comment by owenvoke** [comment]
It already has [been available for the last month](https://github.com/owenvoke/blade-fontawesome/blob/main/resources/svg/brands/x-twitter.svg). 👍🏻

Try using `<x-fab-x-twitter>`

I'm pretty sure that site search doesn't get updated particularly often.

**Comment by berdancanyet** [comment]
Thanks so much for the information, @owenvoke !
