### ISSUE TITLE
Request to tag new release for Font Awesome v6.5.1 (and fix PDF icon bug)

### ISSUE THREAD

**Issue by huubvdw** [owenvoke/blade-fontawesome#69]
### Description

See https://github.com/FortAwesome/Font-Awesome/issues/20017

### Possible implementation

Main branch is already up to date. Can you tag a new release? Thanks in advance!

**Comment by owenvoke** [comment]
Hi @huubvdw, I will release this shortly. 👍🏻

**Comment by owenvoke** [comment]
Released v2.5.1 👍🏻
