### ISSUE TITLE
Extra styling on icons, like fa-spin and fa-spin-pulse

### ISSUE THREAD

**Issue by ssssteve** [owenvoke/blade-fontawesome#75]
### Description

Tried adding fa-spin as a class, but no change. Is there a way to do this currently or is this a potential new feature? Could extra styling classes be added via another parameter?

### Possible implementation

<x-fas-circle-notch extra="fas-spin" class="text-blue-700 h-16 w-16" />

**Comment by owenvoke** [comment]
As far as I know, applying the class should work. 🤔 However, the CSS or JS behind that functionality is needed as well.

For example, to have a basic spinner, you can use:

```blade
<style>
    .fa-spin {
        animation: fa-spin 1.2s linear infinite;
    }

    @keyframes fa-spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>
<x-fas-cloud style="width: 20px; height: 20px;" class="fa-spin"/>
```
