### ISSUE TITLE
Use alternative syntax?

### ISSUE THREAD

**Issue by ssssteve** [owenvoke/blade-fontawesome#76]
### Description

blade-ui-kit allows alternative syntax using for accessing icons:

`@svg('camera', 'icon-lg')`

Is there any alternative syntax here? My use case is this: I have a number of different icons depending on a config array. I'd like to call the icon programmatically using a variable rather than specifically via a component.

### Possible implementation

`<x-fas-users/>`

versus

`@svg($menuIcon, ['class' => 'icon-lg'])`

**Comment by owenvoke** [comment]
I'm pretty sure that should just work. This packages uses Blade Icons under the hood. So I think just using `@svg` should work.

```blade
@svg('fas-cloud', 'w-6 h-6')
```
