### ISSUE TITLE
FontAwesome Pro via font instead of raw .svgs?

### ISSUE THREAD

**Issue by ogroves** [owenvoke/blade-fontawesome#84]
### Description

Wondering if it would be possible to import and use the pro font file, instead of manually importing the raw svgs?

### Possible implementation

`@import '/node_modules/@fortawesome/fontawesome-pro/css/all.css';`

**Comment by owenvoke** [comment]
I think this would be a different package. 🤔 Blade Icons is intended for SVGs.

**Comment by ogroves** [comment]
Thanks for getting back to me so quickly @owenvoke 🫡

Makes sense, I wasn't sure how the free fontawesome kit was imported but if it's all .svgs then I guess there's no workaround here.
