### ISSUE TITLE
Deprecated Errors with PHP 8.4 Compatibility in thecodingmachine/safe

### ISSUE THREAD

**Issue by radimnemecek** [owenvoke/blade-fontawesome#87]
### What happened?

Using thecodingmachine/safe with PHP 8.4 results in deprecated warnings related to implicitly nullable parameters, causing compatibility issues.

<img width="1470" alt="Snímek obrazovky 2024-11-10 v 14 43 27" src="https://github.com/user-attachments/assets/92b30a91-1baf-4152-b8bd-851364caec94">

### Library version

2.7.0

### PHP version

8.4.0 RC3

### What operating systems are you seeing the problem on?

macOS, Windows

**Comment by owenvoke** [comment]
This is an issue with the Safe package, not with this package. 👀 https://github.com/thecodingmachine/safe/pull/441

Feel free to upvote that, and follow the progress there. 👍🏻

**Comment by shish** [comment]
`thecodingmachine/safe` hasn't had any meaningful updates for years -- I'm personally considering it abandoned, and have switched to my more-maintained php8-compatible fork at https://github.com/shish/safe , which is marked as a drop-in replacement for easy migration

**Comment by takashato** [comment]
> This is an issue with the Safe package, not with this package. 👀 [thecodingmachine/safe#441](https://github.com/thecodingmachine/safe/pull/441)
> 
> Feel free to upvote that, and follow the progress there. 👍🏻

It seems that dependency is abandoned. If we just wait for it to be fixed the problem may persist forever for PHP 8.4. Maybe we should find for another solution or use a fork of that package.

**Comment by owenvoke** [comment]
I'll have a look at switching over to the fork on Monday. 👍🏻 Or just dropping it completely.

**Comment by owenvoke** [comment]
Released v2.8.0 which removes the Safe package, and implements a simpler solution (it seems unnecessary to pull in a larger library for 2 functions).

This version also updates to Font Awesome v6.7.1 👍🏻
